### ISSUE TITLE
'jq: error (at /github/workflow/event.json:179): Cannot iterate over null (null)'

### ISSUE THREAD

**Issue by brunojadami** [wyozi/download-gh-release-asset#1]
Hi,

I am trying to use this with the new yaml format, I have a release tagged with 'libraries' and a 'libraries.tar.gz' asset:

```
name: Install Libraries
on: [push, pull_request]

jobs:

  install_libraries:
    runs-on: ubuntu-18.04
    steps:
    - name: download libraries
      uses: wyozi/download-gh-release-asset@master
      with:
        args: libraries.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

But when running I get that error: 

> 'jq: error (at /github/workflow/event.json:179): Cannot iterate over null (null)'

Any ideas?

Thanks in advance
